#ifndef CONSTANTS_H
#define	CONSTANTS_H

#define LIFEPO
//#define LIION

#ifdef LIFEPO
// LiFePo4 24V (8s))
#define INITIAL_FULL_CAP 40000
#define BAT_VOLTAGE_EMPTY 20000
#define BAT_VOLTAGE_FULL 28000
#endif

#ifdef LIION
// LiIon 18650 (10S5P)
#define CELL_CAP 2900
#define CELLS_PARALLEL 5
#define CELLS_SERIAL 10
#define INITIAL_FULL_CAP (CELL_CAP * CELLS_PARALLEL)
#define BAT_VOLTAGE_EMPTY (2.5 * CELLS_SERIAL)
#define BAT_VOLTAGE_FULL (4.2 * CELLS_SERIAL)
#endif

#define MIN_CAP (INITIAL_FULL_CAP / 2)

#define BATT_VOLTAGE_MIN 15000
#define SYS_VOLTAGE_START_CHARGE 13500
#define SYS_VOLTAGE_STOP_CHARGE 13200
#define SYS_VOLTAGE_START_SUPPLY 12700
#define SYS_VOLTAGE_STOP_SUPPLY 12900
#define SYS_VOLTAGE_MIN 10000
#define SYS_VOLTAGE_MAX 15000
#define CHARGING_MIN_TEMP 50
#define HEATER_TEMP 70
#define MAX_TEMP 500
#define BAT_MIN_CHARGE_CURRENT 1000

#define EEPROM_ADDR_CORRECTION_FACTOR 0x04
#define EEPROM_ADDR_AMP_CORRECTION_FACTOR 0x08

#define SENSOR_MEM_COUNT 4

#endif	/* CONSTANTS_H */

